[package]
edition = "2021"
name = "rustdoc-json"
version = "0.8.6"
description = "Utilities for working with rustdoc JSON."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"
documentation = "https://docs.rs/rustdoc-json"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"

[dependencies]
cargo_metadata = "0.17.0"
cargo-manifest = "0.9.0"
serde = { version = "1.0.179", features = ["derive"] }
thiserror = "1.0.44"
toml = "0.7.6"

[dev-dependencies]
assert_cmd = "2.0.12"
expect-test = "1.4.1"
tempfile = "3.7.0"

[dev-dependencies.predicates]
version = "3.0.3"
default-features = false

[dev-dependencies.public-api]
path = "../public-api"
version = "0.31.2"
