[package]
edition = "2021"
name = "rustup-toolchain"
version = "0.1.2"
description = "Utilities for working with rustup toolchains."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/rustup-toolchain"
documentation = "https://docs.rs/rustup-toolchain"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/rustup-toolchain"

[dependencies]
thiserror = "1.0.38"

[dev-dependencies]
expect-test = "1.4.0"

[dev-dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.8.0"

[dev-dependencies.public-api]
path = "../public-api"
version = "0.27.0"
