[package]
edition = "2021"
name = "public-api"
version.workspace = true
description = "List and diff the public API of Rust library crates. Relies on rustdoc JSON output from the nightly toolchain."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/public-api"
documentation = "https://docs.rs/public-api"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/public-api"

[dependencies]
hashbag = { version = "0.1.11", default-features = false }
thiserror = "1.0.44"

[dependencies.serde]
version = "1.0.179"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.104"
features = ["unbounded_depth"]

[dependencies.rustdoc-types]
# path = "/Users/martin/src/rustdoc-types"
version = "0.22.0"

[dev-dependencies]
anyhow = "1.0.75"
assert_cmd = "2.0.12"
expect-test = "1.4.1"
tempfile = "3.8.0"

[dev-dependencies.itertools]
version = "0.11.0"
default-features = false

[dev-dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.8.7"

[dev-dependencies.predicates]
version = "3.0.3"
default-features = false
