[package]
edition = "2021"
name = "public-api"
version.workspace = true
description = "List and diff the public API of Rust library crates. Relies on rustdoc JSON output from the nightly toolchain."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"
documentation = "https://docs.rs/public-api"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"

[dependencies]
hashbag = { version = "0.1.11", default-features = false }
thiserror = "1.0.40"

[dependencies.serde]
version = "1.0.160"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.95"
features = ["unbounded_depth"]

[dependencies.rustdoc-types]
# path = "/Users/martin/src/rustdoc-types"
version = "0.20.0"

[dev-dependencies]
anyhow = "1.0.70"
assert_cmd = "2.0.10"
expect-test = "1.4.1"
tempfile = "3.5.0"
itertools = { version = "0.10.5", default-features = false }

[dev-dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.8.4"

[dev-dependencies.predicates]
version = "3.0.2"
default-features = false
