[package]
edition = "2021"
name = "cargo-public-api"
version.workspace = true
default-run = "cargo-public-api"
description = "List and diff the public API of Rust library crates between releases and commits. Detect breaking API changes and semver violations via CI or a CLI."
homepage = "https://github.com/Enselic/cargo-public-api"
documentation = "https://docs.rs/cargo-public-api"
readme = "../README.md"
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api"

[dependencies]
nu-ansi-term = "0.48.0"
anyhow = "1.0.71"
is-terminal = "0.4.7"
cargo-manifest = "0.9.0"
cargo-util = "0.2.4"
clap_complete_command = "0.5.1"
diff = "0.1.13"
dirs = "5.0.0"
home = "0.5.5"
rustc-hash = "1.1.0"
semver = "1.0.17"
thiserror = "1.0.40"
cargo_metadata = "0.15.4"
toml = "0.7.4"

[dependencies.clap]
version = "4.3.4"
features = ["derive", "wrap_help"]

[dependencies.curl]
version = "0.4.44"

[dependencies.hex]
version = "0.4.3"
features = ["serde"]

[dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.8.6"

[dependencies.public-api]
path = "../public-api"
version = "0.31.2"

[dependencies.serde]
version = "1.0.164"
features = ["rc"]

[dependencies.serde_json]
version = "1.0.97"
default-features = false

[dependencies.smol_str]
version = "0.2.0"
features = ["serde"]

[dev-dependencies.rustup-toolchain]
path = "../rustup-toolchain"
version = "0.1.5"

[dev-dependencies.predicates]
version = "3.0.3"
default-features = false

[dev-dependencies.chrono]
version = "0.4.26"
default-features = false
features = ["std"]

[dev-dependencies]
assert_cmd = "2.0.11"
expect-test = "1.4.1"
remove_dir_all = "0.8.2"
tempfile = "3.6.0"
cargo_metadata = "0.15.4"
