[package]
edition = "2021"
name = "cargo-public-api"
version.workspace = true
default-run = "cargo-public-api"
description = "List and diff the public API of Rust library crates between releases and commits. Detect breaking API changes and semver violations via CI or a CLI."
homepage = "https://github.com/Enselic/cargo-public-api"
documentation = "https://docs.rs/cargo-public-api"
readme = "../README.md"
keywords = ["cargo-subcommand", "semver", "rustdoc-json", "diff"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api"

[dependencies]
nu-ansi-term = "0.50.0"
anyhow = "1.0.75"
cargo-manifest = "0.13.0"
cargo-util = "0.2.8"
clap_complete_command = "0.5.1"
diff = "0.1.13"
dirs = "5.0.0"
home = "0.5.9"
rustc-hash = "1.1.0"
semver = "1.0.18"
thiserror = "1.0.44"
cargo_metadata = "0.18.1"
toml = "0.8.10"

[dependencies.clap]
version = "4.5.0"
features = ["derive", "wrap_help"]

[dependencies.curl]
version = "0.4.46"

[dependencies.hex]
version = "0.4.3"
features = ["serde"]

[dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.8.9"

[dependencies.public-api]
path = "../public-api"
version = "0.33.1"

[dependencies.serde]
version = "1.0.179"
features = ["rc"]

[dependencies.serde_json]
version = "1.0.104"
default-features = false

[dependencies.smol_str]
version = "0.2.1"
features = ["serde"]

[dev-dependencies.rustup-toolchain]
path = "../rustup-toolchain"
version = "0.1.6"

[dev-dependencies.predicates]
version = "3.1.0"
default-features = false

[dev-dependencies.chrono]
version = "0.4.35"
default-features = false
features = ["std"]

[dev-dependencies]
assert_cmd = "2.0.14"
expect-test = "1.4.1"
remove_dir_all = "0.8.2"
tempfile = "3.10.1"
cargo_metadata = "0.18.1"
