[package]
edition = "2021"
name = "cargo-public-api"
version.workspace = true
default-run = "cargo-public-api"
description = "List and diff the public API of Rust library crates between releases and commits. Detect breaking API changes and semver violations via CI or a CLI."
homepage = "https://github.com/Enselic/cargo-public-api"
documentation = "https://docs.rs/cargo-public-api"
readme = "../README.md"
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api"

[features]
default = ["diff-latest"]
# Enable `cargo public-api diff latest`. Requires 33 more deps (most notably the
# `git2` crate) so that the crates.io index can be updated and read.
diff-latest = ["dep:crates-index"]

[dependencies]
nu-ansi-term = "0.46.0"
anyhow = "1.0.69"
is-terminal = "0.4.4"
cargo-manifest = "0.7.1"
clap_complete_command = "0.5.1"
diff = "0.1.13"
dirs = "4.0.0"
home = "0.5.4"
semver = "1.0.17"
thiserror = "1.0.39"
cargo_metadata = "0.15.3"
toml = "0.7.2"
serde = { version = "1.0.155", features = ["derive"] }

[dependencies.clap]
version = "4.0.32"
features = ["derive", "wrap_help"]

[dependencies.crates-index]
version = "0.19.7"
default-features = false
optional = true

[dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.8.2"

[dependencies.public-api]
path = "../public-api"
version = "0.27.3"

[dev-dependencies.rustup-toolchain]
path = "../rustup-toolchain"
version = "0.1.3"

[dev-dependencies.predicates]
version = "2.1.5"
default-features = false

[dev-dependencies]
assert_cmd = "2.0.8"
expect-test = "1.4.1"
pretty_assertions = "1.3.0"
remove_dir_all = "0.8.1"
tempfile = "3.4.0"
cargo_metadata = "0.15.3"
serde_json = "1.0.94"
