# This workflow triggers auto-merge of any PR that dependabot creates so that
# PRs will be merged automatically without maintainer intervention if CI passes
name: Auto-merge dependabot PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-merge:
    if: github.repository == 'Enselic/cargo-public-api' && startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          gh pr review ${{ github.event.pull_request.number }} --comment --body "Hi, I am a bot, and now I am triggering auto-merge of this dependabot PR. This means that if CI passes, this PR will be automatically merged."
      - run: |
          gh pr merge --auto --rebase ${{ github.event.pull_request.number }}

