# This workflow triggers auto-merge of any PR that dependabot creates so that
# PRs will be merged automatically without maintainer intervention if CI passes
name: Auto-merge dependabot PRs

on:
  pull_request_target:
    types: [opened]
    branches:
      - 'dependabot/**'

jobs:
  auto-merge:
    if: github.repository == 'Enselic/cargo-public-api'
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review --comment "Hi, I am a bot, and now I am triggering up auto-merge of this dependabot PR. This means that if CI passes, this PR will be automatically merged." ${{ github.event.pull_request.number }}
      - run: echo gh pr merge --auto --rebase ${{ github.event.pull_request.number }}
