name: CI

on:
  workflow_call: # From .github/workflows/Release.yml, .github/workflows/Nightly.yml
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    name: cargo fmt -- --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  cargo-doc:
    name: RUSTDOCFLAGS='--deny warnings' cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: RUSTDOCFLAGS='--deny warnings' cargo doc --locked --no-deps --document-private-items

  cargo-clippy:
    name: cargo clippy -- --deny clippy::all --deny clippy::pedantic ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: scripts/cargo-clippy.sh

  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    name: cargo test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --locked
      - run: cargo build --locked --no-default-features # Build without "diff-latest" feature
