name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  # The purpose of this job is to detect problems like
  # https://github.com/Enselic/cargo-public-api/issues/61 ourselves
  cargo-install:
    runs-on: ubuntu-latest
    steps:
    - run: cargo install public-api
    - run: cargo install cargo-public-api

  # The purpose of running every night is to detect when a change to
  # https://github.com/rust-lang/rust/tree/master/src/rustdoc-json-types
  # requires that we release a new version of public-api to be compatible with
  # the latest nightly toolchain
  ci:
    uses: ./.github/workflows/CI.yml

  # If Rust nightly changes output, auto-create a PR with the new blessed
  # output, which maintainers can conveniently merge after manual review
  auto-bless:
    environment: CICD-fork
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
    - uses: Swatinem/rust-cache@v2
    - run: ./scripts/bless.sh
    - id: latest-nightly
      run: echo "::set-output name=version::nightly-$(date +'%Y-%m-%d')"
    - uses: peter-evans/create-pull-request@v4
      with:
        title: Bless `${{ steps.latest-nightly.outputs.version }}` output
        commit-message: Bless `${{ steps.latest-nightly.outputs.version }}` output
        author: EnselicCICD <junta-pixlar0l@icloud.com>
        body: Automatically created by ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}
        token: ${{ secrets.ENSELICCICD_GITHUB_TOKEN }}
        push-to-fork: EnselicCICD/cargo-public-api
