name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  # The purpose of this job is to detect problems like
  # https://github.com/Enselic/cargo-public-api/issues/61 ourselves
  cargo-install:
    runs-on: ubuntu-latest
    steps:
    - run: cargo install public-api
    - run: cargo install cargo-public-api


  # The purpose of running every night is to detect when a change to
  # https://github.com/rust-lang/rust/tree/master/src/rustdoc-json-types
  # requires that we release a new version of public-api to be compatible with
  # the latest nightly toolchain
  ci:
    uses: ./.github/workflows/CI.yml

  # If Rust nightly changes output, auto-create a PR with the new blessed
  # output, which maintainers can conveniently merge after manual review
  auto-bless:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
    - uses: Swatinem/rust-cache@v2
    - run: ./scripts/auto-bless.sh
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
